// Auto-generated by sanitizeGeneratedFiles
export async function onRequest(context) {
  const { request } = context;
  try {
    const data = await request.json();
    const { careerField, experience, education } = data;
    if (!careerField || !experience || !education) {
      return new Response("Invalid input", { status: 400 });
    }
    const response = await fetch('/generateResume', {
      method: 'POST',
      body: JSON.stringify(data),
      headers: { 'Content-Type': 'application/json' },
    });
    return response;
  } catch (error) {
    return new Response("Error handling user input", { status: 500 });
  }
}

export async function onRequest(context) {
  const { request } = context;
  try {
    const { method } = request;
    if (method === 'POST') {
      const sessionId = crypto.randomUUID();
      return new Response(JSON.stringify({ sessionId }), {
        headers: { "Content-Type": "application/json" },
      });
    } else if (method === 'GET') {
      const url = new URL(request.url);
      const sessionId = url.searchParams.get('sessionId');
      if (!sessionId) {
        return new Response("Session ID required", { status: 400 });
      }
      const isValid = true; // Replace with actual validation logic
      return new Response(JSON.stringify({ isValid }), {
        headers: { "Content-Type": "application/json" },
      });
    } else {
      return new Response("Method not allowed", { status: 405 });
    }
  } catch (error) {
    return new Response("Error managing session", { status: 500 });
  }
}

export async function onRequest(context) {
  try {
    const branding = {
      name: "ResuMagic AI",
      tagline: "Crafting Resumes with Precision and Style",
      colors: ["#4A90E2", "#50E3C2", "#F5A623", "#D0021B"],
      logoUrl: "https://oaidalleapiprodscus.blob.core.windows.net/private/org-eeM7RLe3Wv2HZ7Toub47POas/user-rnGwZEmjnwoUoF8lEvadvt0O/img-BmVW3mXCADZB1bm7qQaoq9aJ.png?st=2025-08-05T23%3A23%3A21Z&se=2025-08-06T01%3A23%3A21Z&sp=r&sv=2024-08-04&sr=b&rscd=inline&rsct=image/png&skoid=cc612491-d948-4d2e-9821-2683df3719f5&sktid=a48cca56-e6da-484e-a814-9c849652bcb3&skt=2025-08-05T19%3A56%3A22Z&ske=2025-08-06T19%3A56%3A22Z&sks=b&skv=2024-08-04&sig=/k11EBUlSTsLPXTcgxYozI390oTPm8gf4vXIALp8CPA%3D",
    };
    return new Response(JSON.stringify(branding), {
      headers: { "Content-Type": "application/json" },
    });
  } catch (error) {
    return new Response("Error fetching branding info", { status: 500 });
  }
}